# Generated by Django 5.0.3 on 2024-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField()),
                ('certification_name', models.CharField(max_length=100)),
                ('issuing_organizationn', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=True)),
                ('certificate', models.CharField(max_length=255)),
            ],
        ),
    ]
