# Generated by Django 5.0.3 on 2024-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_applicantcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantIntership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_intership_id', models.IntegerField()),
                ('comany_name', models.IntegerField(max_length=100)),
                ('position_title', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=True)),
                ('end_date', models.DateField(default=True)),
                ('description', models.TextField()),
                ('intership_certificate', models.CharField(max_length=2558)),
            ],
        ),
    ]
