# Generated by Django 5.0.3 on 2024-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_applicantintership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantintership',
            name='comany_name',
            field=models.CharField(max_length=100),
        ),
    ]
