# Generated by Django 5.0.3 on 2024-09-02 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_applicantintership_comany_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(default=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('martial_status', models.CharField(max_length=30)),
                ('home_town', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('current_location', models.CharField(max_length=400)),
                ('resume', models.CharField(max_length=255)),
                ('preferred_job_type', models.CharField(max_length=255)),
                ('total_years_of_experience', models.IntegerField()),
                ('availability_to_join', models.CharField(max_length=20)),
                ('work_permit_for_USA', models.BooleanField()),
                ('langauages', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=1000)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
