# Generated by Django 5.0.3 on 2024-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='preferred_job_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='preferred_job_type',
            field=models.CharField(max_length=100),
        ),
    ]
